services:
  postgres:
    image: postgres:16.10-bookworm
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abcd1234
    ports:
      - "5432:5432"

    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: {}
